print("***** Different format symbols******")
print(" my name is %s and my age is %d " %("Goms", 29))
print("decimal number %d " %45)
print("floating point %f " %2.58)
print("floating point %f " %258)
print("single character %c " %"a")
print("hexadecimal %X " %21)
print("Octal %o " %21)
print("exponential %e " %21)
