print("*******Builtin functions in string*********")
text = "THIS IS Ggomathi"
print("first character to upper case - Capitalize output :", text.capitalize())
print("text to lower case - casefold output : ", text.casefold())
print("Center output: ", text.center(60))
print("count :", text.count('S'))
print("encode :", text.encode())
print("endswith :", text.endswith('I'))
print("expandtabs : ", text.expandtabs())
print("find a character :", text.find('G'))
print("Format :", text.format())
print("Format map :", text.format_map('i'))
print("index :", text.index('H'))
print("is all value is alphanumeric :", text.isalnum())
print("is all values are alpha :", text.isalpha())
print("is digital :", text.isdigit())
print("decimal :", text.isdecimal())
print("identifier :", text.isidentifier())
print("lower :", text.islower())
print("numeric :", text.isnumeric())
print("printable :", text.isprintable())
print("space :", text.isspace())
print("title :", text.istitle())
print("upper :", text.isupper())
print("Join :", text.join('wwwww'))
print("ljust :", text.ljust(90))
print("lower :", text.lower())
print("lstrip :", text.lstrip())
#print("make trans :", text.maketrans(5))
print("Strip :", text.strip())
print("starts with :", text.startswith('T'))
print("Swapcase :", text.swapcase())
print("Translate :", text.translate('I'))
print("upper :", text.upper())
print("zfill :", text.zfill(7))
print("splitlines :", text.splitlines())
print("Split :", text.split())
print("join :", text.join('**'))
print("replace :", text.replace('I', 'i'))
print("Partition :", text.partition('i'))
print("length :", len(text))
print("ascii :", ascii(text))
print("Bool :", bool(text))

